name: Push to main workflow

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install ceedling
      run: sudo gem install ceedling
    - name: run tests
      run: ceedling test:all

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      if: always()
      with:
        files: build/artifacts/**/*.xml
