name: Push to main workflow

on:
  push:
    branches: [ main ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:

    # Install GCovr
    - name: Install GCovr
      run: |
        sudo pip install gcovr

    # Install Ceedling
    - name: Install Ceedling
      run: sudo gem install ceedling

    # Check out repository
    - name: Checkout Repo
      uses: actions/checkout@v2

    # Run tests with coverage report
    - name: run tests with coverage
      run: ceedling gcov:all utils:gcov

    - name: 'Archive Unit Test Results'
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-results
        path: build/artifacts/gcov/report.xml
        retention-days: 5

    - name: 'Archive Coverage Report'
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-coverage
        path: build/artifacts/gcov/*.html
        retention-days: 5
