name: Manual workflow
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: gem install ceedling
    - name: Run tests
      run: ceedling test:all
